export const button: string;
export const primary: string;
export const dark: string;
export const warning: string;
export const danger: string;
export const success: string;
export const info: string;
export const small: string;
export const oi: string;
