export const console: string;
export const session: string;
export const sessionMenu: string;
export const sessionFullscreen: string;
export const pre: string;
export const sessionError: string;
export const sessionClose: string;
export const p: string;
export const right: string;
